"use client"
import Head from "next/head";
import { BiUserPlus } from "react-icons/bi";
import Table from "../components/table";
import Form from "../components/form";
import { useState } from "react";
import { QueryClientProvider, QueryClient } from 'react-query';
import { store } from '../redux/store';
import { Provider } from 'react-redux';

const queryClient = new QueryClient();

export default function Home() {

  const [visible, setVisible] = useState(false);

  const handler = () => {
    setVisible(!visible);
  }

  return (
    <QueryClientProvider client={queryClient}>

      <Provider store={store}>
        <section>
          <Head>
            <title>CRUD APP</title>
            <meta name="description" content="Generated by create next app" />
          </Head>
          <main className="py-5">
            <h1 className="text-xl md:text-5xl text-center font-bold py-10">Users management</h1>

            <div className="container mx-auto flex justify-between py-5 border-b">
              <div className="left flex gap-3">
                <button onClick={handler} className="flex bg-indigo-500 text-white px-4 py-2 border rounded-md hover:bg-grary-50 hover:border-indigo-500">
                  Add employee <span className="px-1"><BiUserPlus size={23}></BiUserPlus></span>
                </button>
              </div>
            </div>
            {/* Form */}

            {visible ? <Form></Form> : <></>}

            {/* Table */}
            <div className="container mx-auto">
              <Table></Table>
            </div>
          </main>
        </section>
      </Provider>



    </QueryClientProvider>

  )
}
